from __future__ import annotations

from ..base import SiteConfig, _default_site_config
from ..registry import register_site

@register_site("baothanhhoa")
def build_config() -> SiteConfig:
    """
    Cấu hình cho https://baothanhhoa.vn (Báo Thanh Hóa điện tử).

    - Category chính có path dạng /{slug}.
    - Bài viết chi tiết có URL đuôi ".htm" với slug kết thúc bằng "-<id>.htm".
    - Sapo/description thường nằm trong div.article__sapo.
    """

    return SiteConfig(
        key="baothanhhoa",
        base_url="https://baothanhhoa.vn",
        home_path="/",
        article_name="baothanhhoa",
        max_categories=40,
        max_articles_per_category=80,
        allow_category_prefixes=(
            "/tin24h",
            "/xa-phuong",
            "/thoi-su",
            "/kiem-chung-thong-tin",
            "/dai-bieu-voi-cu-tri",
            "/noi-chinh",
            "/xay-dung-dang",
            "/theo-guong-bac",
            "/nghi-quyet-cua-dang",
            "/tu-tuong-dang",
            "/du-thao",
            "/ve-voi-xu-thanh",
            "/dat-va-nguoi",
            "/khat-vong-thanh-hoa",
            "/diem-den",
            "/mien-tay-thanh-hoa",
            "/kinh-te",
            "/doanh-nghiep",
            "/co-hoi-dau-tu",
            "/kinh-te-thi-truong",
            "/hoi-nhap-quoc-te",
            "/kkt-nghi-son",
            "/sao-mai-group",
            "/xuc-tien-dau-tu",
            "/doi-song-xa-hoi",
            "/giao-duc",
            "/nguoi-tot",
            "/review-ocop",
            "/nong-thon-moi",
            "/an-toan-thuc-pham",
            "/phap-luat",
            "/anttocs",
            "/an-ninh-trat-tu",
            "/van-ban-phap-luat",
            "/the-gioi",
            "/kieu-bao",
            "/ho-so-tu-lieu",
            "/phan-tich-binh-luan",
            "/van-hoa-giai-tri",
            "/dien-anh",
            "/du-lich",
            "/nhip-song-tre",
            "/the-thao",
            "/the-thao-trong-tinh",
            "/the-thao-trong-nuoc",
            "/the-thao-quoc-te",
            "/quoc-phong-an-ninh",
            "/khoa-hoc-cong-nghe",
            "/cong-nghe-moi",
            "/moi-truong",
            "/chuyen-doi-so",
            "/y-te-suc-khoe",
            "/tu-van-suc-khoe",
            "/thuoc-dinh-duong",
            "/khoe-dep",
            "/nhung-dia-chi-tam-long",
            "/xe",
            "/thi-truong-xe",
            "/tu-van-xe",
            "/bat-dong-san-kien-truc",
            "/thi-truong",
            "/tin-tuc-dai-hoi",
            "/ddci-thanh-hoa",
        ),
        deny_category_prefixes=(
            "/short-video",
            "/truyen-hinh",
            "/bao-in",
            "/multimedia",
            "/emagazine",
            "/infographic",
            "/image",
            "/story",
            "/video",
            "/podcast",
            "/phat-thanh",
            "/doc-gia",
            "/docbao",
            "/bao-hang-thang",
        ),
        deny_exact_paths=("/",),
        allowed_locales=("vi", "vi-vn"),
        allowed_article_url_suffixes=(".htm",),
        allowed_article_path_regexes=(r"-\d+\.htm$",),
        deny_article_prefixes=(
            "/video/",
            "/podcast/",
            "/short-video/",
            "/truyen-hinh/",
            "/phat-thanh/",
            "/multimedia/",
            "/emagazine/",
            "/infographic/",
            "/image/",
            "/story/",
            "/docbao/",
            "/bao-in/",
        ),
        description_selectors=(
            "div.article__sapo",
            "meta[name='description']",
            "meta[property='og:description']",
        ),
    )

