from __future__ import annotations

from ..base import SiteConfig, _default_site_config
from ..registry import register_site

@register_site("nhandan")
def build_config() -> SiteConfig:
    return SiteConfig(
        key="nhandan",
        base_url="https://nhandan.vn",
        home_path="/",
        article_name="nhandan",
        deny_exact_paths=("/",),
        deny_category_prefixes=(
            "/mua-bao.html",
            "/tin-moi.html",
            "/dia-phuong.html",
            "/chinhtri",
            "/binh-luan-phe-phan",
            "/xay-dung-dang",
            "/chungkhoan",
            "/thong-tin-hang-hoa",
            "/bhxh-va-cuoc-song",
            "/nguoi-tot-viec-tot",
            "/phapluat",
            "/binh-luan-quoc-te",
            "/chau-phi",
            "/trung-dong",
            "/chau-a-tbd",
            "/goc-tu-van",
            "/khoahoc-congnghe",
            "/phong-chong-toi-pham-cong-nghe-cao-2025",
            "/moi-truong",
            "/duong-day-nong",
            "/dieu-tra-qua-thu-ban-doc",
            "/factcheck",
            "/tri-thuc-chuyen-sau.html",
            "/54-dan-toc",
            "/e-magazine",
            "/multimedia",
            "/video-chinh-tri",
            "/video-kinh-te",
            "/video-van-hoa",
            "/video-xa-hoi",
            "/video-phap-luat",
            "/video-du-lich",
            "/video-the-gioi",
            "/video-the-thao",
            "/video-giao-duc",
            "/video-y-te",
            "/video-khcn",
            "/video-moi-truong",
            "/giaoduc-infographic",
            "/trung-du-va-mien-nui-bac-bo",
            "/dong-bang-song-hong",
            "/trang-bac-trung-bo-va-duyen-hai-trung-bo",
            "/trang-tay-nguyen",
            "/trang-dong-nam-bo",
            "/trang-dong-bang-song-cuu-long",
            "/chu-de.html",
            "/gioi-thieu.html",
        ),
    )

